apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: { }
  template:
    metadata:
      labels:
        io.kompose.network/spring-boot-project: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: example
          image: spring-boot-project_backend:latest
          imagePullPolicy: Never
          name: backend
          ports:
            - containerPort: 8080
          resources: { }
          command: [ "/bin/sh" ]
          args: [ "-c", "while true; do touch /tmp/heartbeat.txt; sleep 5; done;" ]
          livenessProbe:
            exec:
              command:
                - test `find /tmp/heartbeat.txt -mmin -1`
            initialDelaySeconds: 5
            periodSeconds: 30
      restartPolicy: Always
