apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: myapp-test
  labels:
    io.kompose.service: db-data
  name: db-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: demo
  resources:
    requests:
      storage: 100Mi
