version: "3.1"
services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=example
    networks:
      - spring-boot-project
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-boot-project
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=ZGItd3J6MnoK
    expose:
      - 5432
volumes:
  db-data:
networks:
  spring-boot-project:
